spring:
  port: 10086
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testjoin?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 990201
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:com/mxt/**/dao/*.xml
